import pickle
from PythonServerCode.game_engine.question_engine import GameEngine

# TODO: replace creation of new object with pickling and loading
from PythonServerCode.constants import K


def main():
    # here add the level
    engine = GameEngine()
    # engine.add_item(K.introX1000)
    # engine.add_item(K.questionX1001)
    # engine.add_item(K.questionX1002)
    # engine.add_item(K.questionX1005)
    # engine.add_item(K.questionX1008)
    # engine.add_item(K.questionX1003)
    # engine.add_item(K.questionX1004)
    # engine.add_item(K.questionX1006)
    # engine.add_item(K.questionX1007)
    # engine.add_item(K.questionX1008)
    # engine.add_item(K.questionX1009)
    # engine.add_item(K.questionX1010)
    # engine.add_item(K.questionX1011)
    # engine.add_item(K.level_endA1000)
    # engine.add_item(K.level_endZ1001)
    # engine.add_item(K.level_endZ1002)
    # engine.add_item(K.level_endZ1003)
    # engine.add_item(K.level_endZ1004)
    # engine.add_item(K.level_endZ1006)
    # engine.add_item(K.level_endZ1007)
    # engine.add_item(K.level_endZ1008)
    # file_to_store = open("game_engine_model.pickle", "wb")
    # pickle.dump(engine, file_to_store)
    # file_to_store.close()
    # engine.add_item(K.introX2000)
    # engine.add_item(K.questionX2001)
    # engine.add_item(K.questionX2002)
    # engine.add_item(K.questionX2003)
    # engine.add_item(K.questionX2004)
    # engine.add_item(K.questionX2005)
    # engine.add_item(K.questionX2006)
    # engine.add_item(K.questionX2007)
    # engine.add_item(K.questionX2008)
    # engine.add_item(K.questionX2009)
    # engine.add_item(K.questionX2010)
    # engine.add_item(K.questionX2011)
    # engine.add_item(K.level_endA2000)
    # engine.add_item(K.level_endZ2001)
    # engine.add_item(K.level_endZ2002)
    # engine.add_item(K.level_endZ2003)
    # engine.add_item(K.level_endZ2004)
    # engine.add_item(K.level_endZ2005)
    # engine.add_item(K.level_endZ2006)
    # engine.add_item(K.level_endZ2007)
    # engine.add_item(K.level_endZ2008)
    # engine.add_item(K.level_endZ2009)
    # engine.add_item(K.introX3000)
    # engine.add_item(K.questionX3001)
    # engine.add_item(K.questionX3002)
    # engine.add_item(K.questionX3003)
    # engine.add_item(K.questionX3004)
    # engine.add_item(K.questionX3005)
    # engine.add_item(K.questionX3006)
    # engine.add_item(K.questionX3007)
    # engine.add_item(K.questionX3008)
    # engine.add_item(K.questionX3009)
    # engine.add_item(K.questionX3010)
    # engine.add_item(K.questionX3011)
    # engine.add_item(K.level_endZ3001)
    # engine.add_item(K.level_endZ3002)
    # engine.add_item(K.level_endZ3003)
    # engine.add_item(K.level_endZ3004)
    # engine.add_item(K.level_endZ3005)
    # engine.add_item(K.level_endZ3006)
    # engine.add_item(K.level_endZ3007)


if __name__ == "__main__":
    main()
